config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  get 'flats', to: 'flats#index'
  get '/flats/:id', to: 'flats#show', as: 'flat'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'
require 'json'
# require 'mapbox-gl'


class FlatsController < ApplicationController

  def index
    url = 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'
    @flats = JSON.parse(open(url).read)
  end

  def show
    url = 'https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json'
    flats = JSON.parse(open(url).read)
    id = params[:id]
    @showflat = flats.find { |flat| flat['id'] == id.to_i }
    # geo_url = 'https://api.openweathermap.org/data/2.5/weather?q=London&appid=d34a84befd963dd8e6cc8444aea1d775'



  #   mapboxgl.accessToken = 'd34a84befd963dd8e6cc8444aea1d775';
  #   map =  mapboxgl.Map({
  #     container: 'map',
  #     style: 'mapbox://styles/mapbox/streets-v9',
  #     center: [ @showflat["lat"], @showflat["long"] ],
  #     zoom: 12
  #   });

  #   new mapboxgl.Marker()
  # .setLngLat([ -0.077, 51.533 ])
  # .addTo(map);
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>
<ul>
  <% @flats.each do |flat| %>
    <li>
    <%= flat["name"]%>
    <img src="<%=flat["imageUrl"]%>" alt="image">
    <%= flat["price"] %>
    <%= link_to 'View more', flat_path(flat["id"]) %>
    </li>
  <% end %>
</ul>

app/views/flats/show.html.erb
<%# <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' /> %>

<%= @showflat["name"]%>
<img src="<%=@showflat["imageUrl"]%>" alt="image">
<%= image_tag %>
<%= @showflat["price"] %>
<%# <div id="map" style="height: 300px; width: 600px"></div> %>
<img id="map" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/<%=@showflat["lng"]%>,<%=@showflat["lat"]%>,10.45,0,0/600x1000?access_token=pk.eyJ1IjoiaHVpbGluZzk3IiwiYSI6ImNrdncycHB3bzQ1eDAybnFnaTJuaGZsYXoifQ.cSCV-TihvxkzBnUSWpYRYQ'>
<%# new mapboxgl.Marker()
  .setLngLat([ -0.077, 51.533 ])
  .addTo(map); %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>